name: Mirroring

on:
  push:
    branches:
      - main
      - develop

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: Mirror to ThriveYou
    steps:                                              
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:thriveyou/zypher-auto-parts-production.git
          ssh_private_key:                              
            ${{ secrets.SSH_PRIV_KEY }}



            
